export const CITIES = [
  "Agartala", "Aizawl", "Ajmer", "Akola", "Aligarh", "Prayagraj (Allahabad) ", "Alwar", "Ambala", "Amravati", "Amritsar",
  "Anantapur", "Ankleshwar", "Aurangabad", "Avadi", "Abu Dhabi", "Accra", "Addis Ababa", "Adelaide", "Agra", "Ahmedabad",
  "Algiers", "Amman", "Amsterdam", "Ankara", "Antananarivo", "Asunción", "Athens", "Atlanta", "Auckland", "Austin",
  "Bahadurgarh", "Ballari (Bellary)", "Bareilly", "Bathinda", "Belagavi (Belgaum)", "Bharatpur", "Bharuch", "Bhavnagar",
  "Bhilai", "Bhilwara", "Bhiwandi", "Bhiwani", "Bhubaneswar", "Bhuj", "Bidar", "Bilaspur", "Bokaro Steel City", "Bulandshahr",
  "Baghdad", "Baku", "Baltimore", "Bamako", "Bandung", "Bangalore (Bengaluru)", "Bangkok", "Barcelona", "Basel", "Baton Rouge",
  "Beijing", "Beirut", "Belgrade", "Belo Horizonte", "Benghazi", "Berlin", "Bern", "Bhopal", "Birmingham", "Bogotá",
  "Boston", "Brasília", "Bratislava", "Brazzaville", "Brisbane", "Brussels", "Bucharest", "Budapest", "Buenos Aires",
  "Chandrapur", "Chapra", "Coimbatore", "Cuttack", "Cairo", "Calgary", "Canberra", "Cape Town", "Caracas", "Casablanca",
  "Cebu", "Chandigarh", "Changsha", "Chennai", "Chicago", "Chittagong", "Chongqing", "Colombo", "Columbus", "Copenhagen", "Cordoba",
  "Davanagere", "Dehradun", "Dewas", "Dhanbad", "Dharamsala", "Dibrugarh", "Durg", "Dallas", "Dakar", "Dalian",
  "Dar es Salaam", "Delhi", "Denver", "Detroit", "Dhaka", "Doha", "Dongguan", "Douala", "Dubai", "Dublin", "Durban",
  "Edinburgh", "Edmonton", "Ekurhuleni", "Faridabad", "Farrukhabad", "Firozabad", "Faisalabad", "Florence", "Fort Worth",
  "Frankfurt", "Fukuoka", "Gandhinagar", "Gaya", "Ghaziabad", "Gorakhpur", "Gulbarga (Kalaburagi)", "Guntur", "Gurugram",
  "Gaborone", "Gdansk", "Geneva", "Genoa", "Glasgow", "Goa", "Guadalajara", "Guangzhou", "Guatemala City", "Gujranwala",
  "Haifa", "Hamburg", "Hangzhou", "Hanoi", "Harare", "Havana", "Helsinki", "Ho Chi Minh City", "Hong Kong", "Houston",
  "Hyderabad (India)", "Ibadan", "Incheon", "Indore", "Istanbul", "Izmir", "Jabalpur", "Jalandhar", "Jalgaon", "Jammu",
  "Jamnagar", "Jamshedpur", "Jhansi", "Jodhpur", "Junagadh", "Jakarta", "Jeddah", "Johannesburg", "Kabul", "Kampala",
  "Kanpur", "Karachi", "Kathmandu", "Kazan", "Kigali", "Kingston", "Kinshasa", "Kobe", "Kolkata", "Kuala Lumpur",
  "Kunming", "Kuwait City", "Kyiv", "Kyoto", "Lagos", "Lahore", "Lanzhou", "Las Vegas", "Leeds", "Lima", "Lisbon",
  "London", "Los Angeles", "Louisville", "Luanda", "Lucknow", "Lusaka", "Lyon", "Madrid", "Mahé", "Makassar",
  "Managua", "Manama", "Manaus", "Manila", "Maputo", "Marrakesh", "Marseille", "Mashhad", "Mazatlán", "Medan",
  "Medellín", "Melbourne", "Memphis", "Mexico City", "Miami", "Milan", "Milwaukee", "Minsk", "Mississauga", "Mogadishu",
  "Monrovia", "Monterrey", "Montevideo", "Montreal", "Moscow", "Mumbai", "Munich", "Nairobi", "Nagoya", "Nagpur",
  "Nanjing", "Nanning", "Nagercoil", "Nanded", "Nashik", "Nellore", "Noida", "North Lakhimpur", "Naples", "Nashville",
  "New Delhi", "New Orleans", "New York", "Newark", "Nice", "Ningbo", "Nizhny Novgorod", "Nouakchott", "Novosibirsk",
  "Oklahoma City", "Omaha", "Osaka", "Oslo", "Ottawa", "Panama City", "Paris", "Patna", "Perth", "Philadelphia",
  "Phnom Penh", "Phoenix", "Pittsburgh", "Port Elizabeth", "Port Harcourt", "Port Louis", "Port Moresby", "Portland",
  "Porto", "Prague", "Pretoria", "Pune", "Qingdao", "Quebec City", "Quito", "Raebareli", "Raichur", "Raipur",
  "Rajahmundry", "Rajkot", "Ranchi", "Ratlam", "Rewa", "Rohtak", "Rourkela", "Rabat", "Raleigh", "Recife",
  "Reykjavik", "Richmond", "Rio de Janeiro", "Riyadh", "Rome", "Rosario", "Rotterdam", "Sacramento", "Saint Petersburg",
  "Salt Lake City", "San Antonio", "San Diego", "San Francisco", "San José (Costa Rica)", "San Jose (USA)", "San Juan",
  "San Salvador", "Sana'a", "Santiago", "Santo Domingo", "São Paulo", "Seattle", "Sendai", "Seoul", "Seville",
  "Shanghai", "Sharjah", "Shenzhen", "Shijiazhuang", "Singapore", "Skopje", "Sofia", "St. Louis", "Stockholm", "Stuttgart",
  "Surat", "Suva", "Sydney", "Taipei", "Tallinn", "Tangier", "Tampa", "Tashkent", "Tbilisi", "Tehran", "Tel Aviv",
  "Tianjin", "Tijuana", "Tilburg", "Tokyo", "Toronto", "Tripoli", "Tunis", "Ulaanbaatar", "Valencia", "Vancouver",
  "Varanasi", "Venice", "Vienna", "Vientiane", "Vilnius", "Virginia Beach", "Warsaw", "Washington D.C.", "Wellington",
  "Wenzhou", "Winnipeg", "Wuhan", "Wuxi", "Warangal", "Xiamen", "Xi'an", "Yaoundé", "Yerevan", "Yokohama", "Yamunanagar",
  "Zirakpur", "Zagreb", "Zaragoza", "Zhengzhou", "Zibo", "Zurich"
];
